# ansible-playbook ./cellular_config.yml -e ansible_hosts=nameofhost
- name: Set Cellular Information and Parameters parameters
  hosts: "{{ansible_hosts}}"  # pass as -e ansible_hosts=wti_demo on the commandline
  collections:
     - wti.remote
  connection: local
  gather_facts: False

  tasks:
  - set_fact: use_https=False
    when: use_https is undefined
  - set_fact: validate_certs=False
    when: validate_certs is undefined

  - cpm_cellular_config:
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      cellenable: "{{cellenable}}"
      apn: "{{apn}}"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
